const OPENAI_API_KEY         = 'YOUR_OPENAI_KEY';
const SUPABASE_URL           = 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY      = 'YOUR_SUPABASE_ANON_KEY';
const STRIPE_BUY_BUTTON_ID   = 'YOUR_STRIPE_BUY_BUTTON_ID';
const STRIPE_PUBLISHABLE_KEY = 'YOUR_STRIPE_PUBLISHABLE_KEY';
